 export const categories = [
    "Cosmetics & Makeup",
    "Skin Care",
    "Beverages & Drinks",
    "Fitness & Gym Products",
    "App & Website Promotions",
    "Clothing Brands",
    "Furniture Brands",
    "Food & Beverages",
    "Footwear",
    "Toys & Games",
    "Electronics & Gadgets",
    "Home & Living",
    "Farming & Agriculture",
    "Kitchen Appliances",
    "Pet Products",
    "Beauty & Health",
    "Groceries",
    "Sports & Fitness",
    "Bags & Luggage",
    "Baby Products & Toys",
    "Kids' Fashion",
    "Automotive & Industrial",
    "Books & Literature",
    "Movies & Entertainment",
    "Video Games",
    "Mobiles & Computers",
    "TV & Appliances",
    "Men's Fashion",
    "Women's Fashion",
    "Healthcare & Wellness",
    "Travel & Tourism",
    "Education & E-learning",
    "Real Estate",
    "Jewelry & Accessories",
    "Financial Services",
    "Technology & Software",
    "Art & Design",
    "Music & Instruments",
    "Event Planning",
    "Hospitality & Restaurants",
  ];